services:
  - type: web
    name: landslide-ews-api
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: landslide_ews
      - key: AT_USERNAME
        sync: false
      - key: AT_API_KEY
        sync: false
      - key: AT_SENDER_ID
        sync: false
      - key: OPENTOPO_API_KEY
        sync: false
      - key: OFFICER_PASSWORD
        sync: false
      - key: APP_ENV
        value: production
    healthCheckPath: /health
